### ISSUE TITLE
auth: 'APIUser:APIPass'

### ISSUE THREAD

**Issue by kenshinman** [VeliovGroup/spiderable-middleware#1]
Where do I get this `auth: 'APIUser:APIPass'` ? 

Is it meant to be on server (I implemented on server)

**Comment by dr-dimitru** [comment]
Hello @kenshinman ,

 1. This is widely explained in our [examples section](https://github.com/VeliovGroup/spiderable-middleware/tree/master/examples)
 2. See installation examples at [ostr.io](https://ostr.io/info/prerendering#install-meteor)
 3. Credentials for Prerendering service can be obtained for added hostname [here](https://ostr.io/service/prerender), *note: credentials are individual for each hostname*
 4. Prerendering service and `spiderable-middleware` package is server only

Let me know if this is helpful.

**Comment by dr-dimitru** [comment]
@kenshinman is this one solved?

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue still persists on your end.
