### ISSUE TITLE
Check if prerendering

### ISSUE THREAD

**Issue by nicooprat** [VeliovGroup/spiderable-middleware#4]
(Using Meteor) How can I check whether the code is currently being prerendered or not? Something like `location.href.indexOf('?_escaped_fragment_=')`? Thanks.

**Comment by dr-dimitru** [comment]
Hello @nicooprat ,

Not possible for right now. As we pretend to be a regular browser as much as possible.
We will add this feature in next release.

**Comment by dr-dimitru** [comment]
Hello @nicooprat ,

Sorry for delay with this one.
Now it's possible, see docs:
 - [Detect Prerendering engine requests during runtime](https://github.com/VeliovGroup/ostrio/blob/master/docs/prerendering/detect-prerendering.md)
 - [Detect Prerendering engine requests during runtime (*Meteor specific*)](https://github.com/VeliovGroup/ostrio/blob/master/docs/prerendering/detect-prerendering-meteor.md)

Thank you a lot for contribution 👍 
Feel free to close if this solution fits your needs.

**Comment by nicooprat** [comment]
Thanks to you!
